name: .NET Core

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ${{env.working-directory}}
      run: dotnet test --no-restore --verbosity normal
